version: "3.3"
services:
    showweb:
        container_name: showweb
        image: myreact
        ports:
            # - "80:8001"
            - "80:3000"
        # depends_on:
        #     - backend
        
            
    backend:
      container_name: backend
      image: mydb
      ports:
        # - "443:8101"
        - "8080:8080"
      depends_on:
        - postgres
      environment:
        - POSTGRES_HOST=db_host
        - POSTGRES_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin123
        - POSTGRES_DB=mcqas
        - SECRET_KEY=django-insecure-fyr$qmpwlyhi6f_xnpliot%q+d+3fx)y0pyy@$u-#yf4&*+!fz
        - PEPPER=kmitl
        - EMAIL_HOST_USER=mcqa.system@gmail.com
        - EMAIL_HOST_PASSWORD=tubh bawz zcqy bqdg

    postgres:
      container_name: postgres
      image: postgres
      ports:
        - "5433:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin123
        - POSTGRES_DB=mcqas
      volumes:
        - ./postgres:/var/lib/postgresql/data

